cut_body_after = "" # don't include text from the PR body in the merge commit message
status = [
  "Evaluate flake.nix",
  "check from-nixos [x86_64-linux]",
  "check from-nixos-2211 [x86_64-linux]",
  "check from-nixos-with-sudo [x86_64-linux]",
  "check from-nixos-with-sudo-2211 [x86_64-linux]",
  "check treefmt [x86_64-linux]",
  "deploy",
  "devShell default [x86_64-linux]",
  "package default [x86_64-linux]",
  "package docs [x86_64-linux]",
  "package nixos-anywhere [x86_64-linux]"
]
